language: node_js

cache: npm



# safelist

branches:

  only:

  - master



# TODO: Separate jobs into stages, change environments based on branch

script:

  - npm test
  
  - npm run build
  
  - ~/.npm/_logs/2019-05-19T00_45_42_062Z-debug.log
    
  - sudo pip install -qq awscli awsebcli
  
  - mkdir ~/.aws; echo -e "[weco-iam]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
  
  - npm run deploy:production
 
