language: node_js
cache: npm

# TODO: Separate jobs into stages, change environments based on branch
script:
  - npm test
  - npm run build
  - apt-get update && apt-get install -qq -y python-pip libpython-dev zip
  - curl https://bootstrap.pypa.io/get-pip.py | python
  - pip install -qq awscli awsebcli
  - mkdir ~/.aws; echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
  - node ./config/deploy.js
