language: node_js

cache: npm



# safelist

branches:

  only:

  - master



# TODO: Separate jobs into stages, change environments based on branch

script:

  - npm test
  
  - npm run build:production
  
  - npm install shelljs
  
  - sudo pip install -qq awscli awsebcli

  - mkdir ~/.aws; echo -e "[weco]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
  
  - echo -e "[profile weco]\nregion=eu-west-1\n" > ~/.aws/config
  
  - node ./config/deploy.js master
