language: node_js
cache: npm

stages:
  - test
  - "Build and Deploy"

jobs:
  include:
    - stage: test
      script: npm test
    - stage: "Build and Deploy"
      script:
        - npm run build:dev
        - npm run upload:dev
