language: node_js

cache: npm



# safelist

branches:

  only:

  - master



# TODO: Separate jobs into stages, change environments based on branch

script:

  - npm test
  
  - npm run build:production
  
  - cd public
  
  - cd dist
  
  - ls
    
  - sudo pip install -qq awscli awsebcli
  
  - mkdir ~/.aws; echo -e "[weco-iam]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
  
  - npm run deploy:production
 
